angular.module('pmtViewer', [
    'leaflet-directive', // include common directive
    'chart.js', // include common directive
    'ui.router', // angular require
    'config',        // include the config module generated by the grunt build from app.config.js
    'placeholders',
    'ui.bootstrap',
    'plusOne'
])

.config(function myAppConfig($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/login');
})

.run(function run() {
})

// include the config & global constants from the config module
.controller('AppCtrl', function($scope, $location, $rootScope, config, global) {
    $scope.config = config;  // add the config constat to the rootScope variable
    $scope.global = global;  // add the global constat to the rootScope variable

    $scope.$on('$stateChangeSuccess', function (event, toState, toParams, fromState, fromParams) {
        if (angular.isDefined(toState.data.pageTitle)) {
            $scope.pageTitle = toState.data.pageTitle + ' | PMT';
        }
    });
});

require('./about/about.js');
require('./about/info/info-spatialdev.js');
require('./login/login.js');
require('./template1/template1.js');
require('./template2/template2.js');
require('./template3/template3.js');
